import { Trip } from "./ITrip"

export const trips: Trip[] = [
    {
        tripName: "W krainie bogów",
        country: "Grecja",
        start: "12-06-2023",
        end: "30-06-2023",
        price: 500,
        numberOfPlaces: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/greece.jpg",
    },
    {
        tripName: "Z dala od świata",
        country: "Hawaje",
        start: "17-08-2023",
        end: "02-09-2023",
        price: 700,
        numberOfPlaces: 2,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/hawaii.jpg",
    },
    {
        tripName: "W mieście miłości",
        country: "Paryż",
        start: "17-01-2023",
        end: "02-02-2023",
        price: 3700,
        numberOfPlaces: 6,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/paris.jpg",
    },
    {
        tripName: "Luksusowy wyjazd",
        country: "Austria",
        start: "17-08-2023",
        end: "02-09-2023",
        price: 7000,
        numberOfPlaces: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/austria.jpeg",
    },
    {
        tripName: "Górski klimat",
        country: "Szwajcaria",
        start: "17-05-2023",
        end: "02-06-2023",
        price: 2200,
        numberOfPlaces: 12,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/switzerland.jpg",
    },
    {
        tripName: "Kuchnie świata",
        country: "Azja",
        start: "17-03-2023",
        end: "02-04-2023",
        price: 5600,
        numberOfPlaces: 4,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/asia.jpg",
    },
    {
        tripName: "Winne klimaty",
        country: "Włochy",
        start: "17-10-2023",
        end: "02-11-2023",
        price: 2500,
        numberOfPlaces: 19,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/italy.jpg",
    },
    {
        tripName: "Promienie lata",
        country: "Portugalia",
        start: "18-08-2023",
        end: "02-09-2023",
        price: 1200,
        numberOfPlaces: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/portugese.jpg",
    },
    {
        tripName: "Szukając szczęscia",
        country: "Las Vegas",
        start: "17-06-2023",
        end: "02-07-2023",
        price: 4000,
        numberOfPlaces: 5,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/vegas.jpg",
    },
    {
        tripName: "Willa miłości",
        country: "Werona",
        start: "17-08-2023",
        end: "02-09-2023",
        price: 800,
        numberOfPlaces: 11,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        img: "../assets/images/werona.jpg",
    }
]