// import { Trip } from "./ITrip"

// export const trips: Trip[] = [
//     {
//         id: 1,
//         tripName: "W Krainie Bogów",
//         country: "Grecja",
//         start: "2023-06-12",
//         end: "2023-06-30",
//         price: 500,
//         numberOfPlaces: 10,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/greece.jpg", "../assets/images/greece1.jpeg", "../assets/images/greece2.jpeg"],
//     },
//     {
//         id: 2,
//         tripName: "Z Dala od Świata",
//         country: "Hawaje",
//         start: "2023-08-17",
//         end: "2023-09-02",
//         price: 700,
//         numberOfPlaces: 2,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/hawaii.jpg", "../assets/images/hawaii1.jpg", "../assets/images/hawaii2.jpg", "../assets/images/hawaii3.webp"],
//     },
//     {
//         id: 3,
//         tripName: "W Mieście Miłości",
//         country: "Paryż",
//         start: "2023-01-17",
//         end: "2023-02-02",
//         price: 3700,
//         numberOfPlaces: 6,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/paris.jpg"],
//     },
//     {
//         id: 4,
//         tripName: "Luksusowy Wyjazd",
//         country: "Austria",
//         start: "2023-08-17",
//         end: "2023-09-02",
//         price: 7000,
//         numberOfPlaces: 1,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/austria.jpeg"],
//     },
//     {
//         id: 5,
//         tripName: "Górski Klimat",
//         country: "Szwajcaria",
//         start: "2023-05-17",
//         end: "2023-06-02",
//         price: 2200,
//         numberOfPlaces: 12,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/switzerland.jpg"],
//     },
//     {
//         id: 6,
//         tripName: "Kuchnie Świata",
//         country: "Azja",
//         start: "2023-03-17",
//         end: "2023-04-02",
//         price: 5600,
//         numberOfPlaces: 4,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/asia.jpg"],
//     },
//     {
//         id: 7,
//         tripName: "Winne Klimaty",
//         country: "Włochy",
//         start: "2023-10-17",
//         end: "2023-11-02",
//         price: 2500,
//         numberOfPlaces: 19,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/italy.jpg"],
//     },
//     {
//         id: 8,
//         tripName: "Promienie Lata",
//         country: "Portugalia",
//         start: "2023-08-18",
//         end: "2023-09-02",
//         price: 1200,
//         numberOfPlaces: 8,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/portugese.jpg"],
//     },
//     {
//         id: 9,
//         tripName: "Szukając Szczęscia",
//         country: "Las Vegas",
//         start: "2023-06-17",
//         end: "2023-07-02",
//         price: 4000,
//         numberOfPlaces: 5,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/vegas.jpg"],
//     },
//     {
//         id: 10,
//         tripName: "Willa Miłości",
//         country: "Werona",
//         start: "2023-08-17",
//         end: "2023-09-02",
//         price: 800,
//         numberOfPlaces: 11,
//         description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//         img: ["../assets/images/werona.jpg"],
//     }
// ]